# -*- coding: utf-8 -*-
"""Práctico 4: Estructuras repetitivas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFwUrE4zsgk9i3m6eFFlTkyZdtN6mSGj
"""

#1) Crea un programa que imprima en pantalla todos los números enteros desde 0 hasta 100
#(incluyendo ambos extremos), en orden creciente, mostrando un número por línea.
for i in range(101):
    print(i)

#2) Desarrolla un programa que solicite al usuario un número entero y determine la cantidad de dígitos que contiene.
numero = input("Ingresa un número entero: ")
digitos = len(numero)
print(f"El número tiene {digitos} dígitos.")

#3) Escribe un programa que sume todos los números enteros comprendidos entre dos valores dados por el usuario, excluyendo esos dos valores.
inicio = int(input("Ingresa el primer número: "))
fin = int(input("Ingresa el segundo número: "))

if inicio > fin:
    inicio, fin = fin, inicio

suma = sum(range(inicio + 1, fin))
print(f"La suma de los números entre {inicio} y {fin} es {suma}")

#4) Elabora un programa que permita al usuario ingresar números enteros y los sume en
#secuencia. El programa debe detenerse y mostrar el total acumulado cuando el usuario ingrese un 0.
total = 0

while True:
    numero = int(input("Ingresa un número: "))
    if numero == 0:
        break
    total += numero

print(f"La suma es {total}")

#5) Crea un juego en el que el usuario deba adivinar un número aleatorio entre 0 y 9. Al final, el
#programa debe mostrar cuántos intentos fueron necesarios para acertar el número.
import random

numero_secreto = random.randint(0, 9)
intentos = 0

while True:
    intento = int(input("Adivina el número (entre 0 y 9): "))
    intentos += 1
    if intento == numero_secreto:
        print(f"Adivinaste en {intentos} intentos.")
        break
    else:
        print("Intenta de nuevo.")

#6) Desarrolla un programa que imprima en pantalla todos los números pares comprendidos entre 0 y 100, en orden decreciente.
for i in range(100, -1, -2):
    print(i)

#7) Crea un programa que calcule la suma de todos los números comprendidos entre 0 y un número entero positivo indicado por el usuario.
n = int(input("Ingresa un número: "))

suma = 0
for i in range(n + 1):
  suma += i
print(f"La suma es {suma}")

#8) Escribe un programa que permita al usuario ingresar 100 números enteros. Luego, el
#programa debe indicar cuántos de estos números son pares, cuántos son impares, cuántos son
#negativos y cuántos son positivos. (Nota: para probar el programa puedes usar una cantidad
#menor, pero debe estar preparado para procesar 100 números con un solo cambio).

pares = 0
impares = 0
positivos = 0
negativos = 0

for i in range(100):
    num = int(input(f"Ingrese el número #{i+1}: "))
    if num % 2 == 0:
        pares += 1
    else:
        impares += 1
    if num > 0:
        positivos += 1
    elif num < 0:
        negativos += 1

print(f"\nPares: {pares}")
print(f"Impares: {impares}")
print(f"Positivos: {positivos}")
print(f"Negativos: {negativos}")

#9) Elabora un programa que permita al usuario ingresar 100 números enteros y luego calcule la
#media de esos valores. (Nota: puedes probar el programa con una cantidad menor, pero debe
#poder procesar 100 números cambiando solo un valor).
suma = 0

for i in range(100):
    num = int(input(f"Ingrese el número #{i+1}: "))
    suma += num

media = suma / 3
print(f"\nLa media es: {media}")

#10) Escribe un programa que invierta el orden de los dígitos de un número ingresado por el
#usuario. Ejemplo: si el usuario ingresa 547, el programa debe mostrar 745.
numero = input("Ingresa un número: ")
numero_invertido = numero[::-1]
print(f"El número invertido es: {numero_invertido}")